source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!
pod 'pop'
pod 'SDWebImage'
pod 'PINRemoteImage'
pod 'DACircularProgress'
pod 'SVProgressHUD'
pod 'AsyncDisplayKit'
pod 'TFCamera', :git => 'https://github.com/TimeFaceCoder/TFCamera.git'
