source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!
pod 'pop'
pod 'GPUImage'
pod 'Masonry'
pod 'AsyncDisplayKit'
pod 'SDWebImage'
pod 'PINRemoteImage'
pod 'AFNetworking'
pod 'DACircularProgress'
pod 'SVProgressHUD'
